feat: add goreleaser workflow
kubernetes-sigs/kubectl-validate pull request #76
Opened 2023-10-04 23:06 UTC by eddycharly

This PR add goreleaser workflow and config.

2023-10-04 23:06 UTC, eddycharly commented
cc @apelisse

2023-10-04 23:11 UTC, eddycharly commented
(i didn't try it, could have typos in the config 🤞)

2023-10-04 23:12 UTC, alexzielenski requested changes
Thanks so much for this! Definitely what we were just talking about needing...

2023-10-04 23:12 UTC, alexzielenski commented on .goreleaser.yaml
> +    binary: kyverno-json
probably should change

2023-10-04 23:12 UTC, eddycharly commented on .goreleaser.yaml
> +    binary: kyverno-json
yeah, just saw it 🤦

2023-10-04 23:13 UTC, eddycharly commented on .goreleaser.yaml
> +    binary: kyverno-json
fixed

2023-10-04 23:19 UTC, eddycharly commented
@alexzielenski let me know if you want more config, goreleaser can use cosign, build/sign images with ko, publish on brew, etc...

2023-10-19 16:59 UTC, caesarxuchao commented
Hi all, thanks for starting this PR. What's required to get this PR merged? It would be very helpful to have released binaries of kubectl-validator.

2023-10-19 21:29 UTC, apelisse reviewed
I'm fine to merge this, test and see how it goes, we don't have a lot to lose if it doesn't work perfectly.

2023-10-19 21:29 UTC, apelisse commented on .github/workflows/release.yaml
> +          set -e
What's the point of that `set -e`, will the step not fail if `git fetch` fails anyway?

2023-10-19 21:30 UTC, apelisse commented
/approve
/lgtm

2023-10-19 21:34 UTC, merged

2023-10-26 20:51 UTC, apelisse commented
OK, let's try it now!

2023-10-26 20:54 UTC, apelisse commented
I just pushed v0.0.2 (from the same commit as v0.0.1) and it doesn't look like it's triggering: https://github.com/kubernetes-sigs/kubectl-validate/actions/workflows/release.yaml

2023-11-27 05:10 UTC, caesarxuchao commented
Thanks for trying! Our company is using a forked release so we are not blocked. We'll shift to the official release whenever that's ready.
kubectl-validate has caught numerous issues in our dev workflow. Thanks for creating this super useful tool!