Allow flag local-crds to take a crd file as input
kubernetes-sigs/kubectl-validate pull request #92
Opened 2024-02-23 00:39 UTC by dawnsmile

#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:

This PR allows flag `local-crds` to take a crd file instead of a folder as input

#### Which issue(s) this PR fixes:

Fixes #

N/A

#### Special notes for your reviewer:

#### Does this PR introduce a user-facing change?

```release-note
The flag `local-crds` can take a file instead of a folder as input now.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

2024-02-23 00:46 UTC, eddycharly commented
Thanks @dawnsmile !
Can you elaborate why we would need this ?

2024-02-23 22:09 UTC, dawnsmile commented
> Thanks @dawnsmile ! Can you elaborate why we would need this ?

In my project, I put crd files and other k8s manifests (deployment, rbac, etc) in the same folder. Without this PR, I have to move the crd file into its dedicated folder to make the tool work.

2024-03-14 18:34 UTC, alexzielenski requested changes
I like this idea and think we should move forward. It is backwards compatible change which is nice.

@danwinship are you able to sign the CLA

2024-03-14 18:34 UTC, alexzielenski commented on pkg/openapiclient/local_crds.go
> +		parentPath = filepath.Dir(k.path)
I dont think we should search the file's surrounding directory if just a file was provided

2024-04-01 21:50 UTC, alexzielenski commented
@dawnsmile are you still planning on working on this?

2024-09-08 08:21 UTC, closed without merging